import { BrowserWindow, app, ipcMain } from 'electron';
import started from 'electron-squirrel-startup';
import { join } from 'node:path';

import { Channel } from '_types_';

import { productName } from '../package.json';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (started) {
  app.quit();
}

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    title: `${productName} ${app.getVersion()}`,
    minWidth: 1080,
    minHeight: 720,
    width: 1080,
    height: 720,
    show: false,
    webPreferences: {
      preload: join(__dirname, 'preload.js')
    }
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow
      .loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL)
      .then(() => mainWindow.show());
  } else {
    mainWindow
      .loadFile(
        join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`)
      )
      .then(() => mainWindow.show());
  }

  ipcMain.handle(Channel.COUNTER_INCREMENT, (e, value: number) => value + 1);
  ipcMain.handle(Channel.COUNTER_DECREMENT, (e, value: number) => value - 1);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
